---
title: "Week 6: Code along 5"
subtitle: "CHAPTER 3 Building a Portfolio"
author: "Daniel Lee"
date: "2022-09-19"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r}
# Load packages

# Core
library(tidyverse)
library(tidyquant)

```

## Goal
Collect individual returns into a portfolio by assigning a weight to each stock

five stocks: "SPY", "EFA", "IJS", "EEM", "AGG"

from 2012-12-31 to 2017-12-31

## 1 Import stock prices

```{r}
# Choose stocks

symbols <- c("SPY", "EFA", "IJS", "EEM", "AGG")

# Using tq_get() ----
prices <- tq_get(x = symbols,
                 get = "stock.prices",
                 from = "2012-12-31",
                 to = "2017-12-31")

```

## 2 Convert prices to returns

```{r}
asset_returns_tbl <- prices %>%

    # Calculate monthly returns
    group_by(symbol) %>%
    tq_transmute(select = adjusted,
                 mutate_fun = periodReturn,
                 period = "monthly",
                 type = "log") %>%
    slice(-1) %>%
    ungroup() %>%

    # remane
    set_names(c("asset", "date", "returns"))

# period_returns = c("yearly", "quarterly", "monthly", "weekly")
```

## 3 Assign a weight to each asset

```{r}
symbols <- asset_returns_tbl %>% distinct(asset) %>% pull()

w <- c(0.25,
       0.25,
       0.20,
       0.20,
       0.10)

w_tbl <- tibble(symbols, w)
```

## 4 Build a portfolio

```{r}
portfolio_returns_rebalanced_monthly_tbl <- asset_returns_tbl %>%
    
    tq_portfolio(assets_col   = asset,
                 returns_col  = returns,
                 weights      = w_tbl,
                 col_rename   = "returns",
                 rebalance_on = "months")

portfolio_returns_rebalanced_monthly_tbl

# write_rds(portfolio_returns_rebalanced_monthly_tbl,
#           "00_data/Ch03_portfolio_returns_rebalanced_monthly_tbl.rds")
```

## 5 Plot

```{r}
portfolio_returns_rebalanced_monthly_tbl %>%
    
    ggplot(aes(x = date, y = returns)) +
    geom_point(color = "cornflower blue") +
    
    # Formatting
    scale_x_date(breaks = scales::breaks_pretty(n = 6)) +
    
    labs(title = "Portfolio Returns Scatter",
         y = "monthly return")


portfolio_returns_rebalanced_monthly_tbl %>%
    
    ggplot(aes(returns)) +
    geom_histogram(fill = "cornflower blue",
                   binwidth = 0.005) +
    
    labs(title = "Portfolio Returns Distribution",
         y = "count",
         x = "returns")


portfolio_returns_rebalanced_monthly_tbl %>%
    
    ggplot(aes(returns)) +
    geom_histogram(fill = "cornflower blue",
                   binwidth = 0.01) +
    geom_density(aes(returns)) +
    
    labs(title = "Portfolio Histogram and Density",
         y = "distribution",
         x = "monthly returns")

```

