---
title: "Portfolio Returns"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

# Shiny
library(flexdashboard)
library(shiny)
library(DT)

# Core
library(tidyverse)
library(tidyquant)

```






User Input {.sidebar}
-----------------------------------------------------------------------

```{r}
textInput("stock1", "Stock 1", "SPY")

```



Column 
-----------------------------------------------------------------------

### text input

```{r}
output$symbol <- renderPrint(input$stock1)

textOutput(outputId = "symbol")

```




Column {.tabset .tabset-fade}
-----------------------------------------------------------------------

```{r}
# event reactive filter

asset_prices_tbl <- reactive({
    
    ## 1 Import stock prices ----
    
    symbols <- c(input$stock1)
    
    tq_get(x = symbols,
           get = "stock.prices",
           from = "2012-12-31",
           to = "2017-12-31") 
    

})

```

### Table

```{r}
renderPrint(asset_prices_tbl())
```


### Histogram

```{r}


```

