---
title: "Asset Returns"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
# Load packages

# Core
library(tidyverse)
library(tidyquant)

# Interactive web app
library(flexdashboard)
library(shiny)

# Interactive visualization
library(plotly)

# Interactive data table
library(DT)
```




```{r}
## 1 Import stock prices

# Choose stocks

symbols <- c("SPY", "EFA", "IJS", "EEM", "AGG")

# Using tq_get() ----
prices <- tq_get(x = symbols,
                 get = "stock.prices",
                 from = "2012-12-31",
                 to = "2017-12-31")

```



```{r}
## 2 Convert prices to returns

asset_returns_tbl <- prices %>%

    # Calculate monthly returns
    group_by(symbol) %>%
    tq_transmute(select = adjusted,
                 mutate_fun = periodReturn,
                 period = "monthly",
                 type = "log") %>%
    slice(-1) %>%
    ungroup() %>%

    # remane
    set_names(c("asset", "date", "returns"))

# period_returns = c("yearly", "quarterly", "monthly", "weekly")
```




```{r}
## 3 Make plot
g <- asset_returns_tbl %>%

    ggplot(aes(x = returns)) +
    geom_density(aes(col = asset), alpha = 1, show.legend = FALSE) +
    geom_histogram(aes(fill = asset), alpha = 0.45, binwidth = 0.01) +
    facet_wrap(~asset, ncol = 1) +
    guides(fill = "none") +

    labs(title = "Monthly Returns since 2013",
         x = "distribution",
         y = "monthly returns") +
    theme_update(plot.title = element_text(hjust = 0.5))
```


```{r}
library(ggridges)

## 3 Make plot
g_ridge <- asset_returns_tbl %>%

    ggplot(aes(x = returns, y = asset, fill = asset)) +
    geom_density_ridges() +
    guides(fill = "none") +

    labs(title = "Monthly Returns since 2013",
         x = "distribution",
         y = "monthly returns") +
    theme_update(plot.title = element_text(hjust = 0.5))
```
Column {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Plot

```{r}
ggplotly(g)
```

### Plot ridge

```{r}
ggplotly(g_ridge)
```


### Table

```{r}
DT::datatable(asset_returns_tbl) %>% formatPercentage("returns", digits = 2)
```

